# Generated by Django 5.1.11 on 2026-06-20 23:04

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('role', models.CharField(blank=True, choices=[('member', 'Member'), ('manager', 'Manager')], default='', help_text='Role for regular users. Staff/superuser use is_staff/is_superuser.', max_length=30, verbose_name='Role')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone number')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone verified')),
                ('profile_picture', models.ImageField(blank=True, default='', upload_to=core.models.profile_picture_upload_path, verbose_name='Profile picture')),
                ('timezone', models.CharField(blank=True, choices=core.models.get_timezone_choices, default='UTC', max_length=50, verbose_name='Timezone')),
                ('preferred_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System (auto)')], default='system', max_length=10, verbose_name='Preferred theme')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Invitation sent at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspended at')),
                ('suspended_until', models.DateTimeField(blank=True, null=True, verbose_name='Suspended until')),
                ('suspension_reason', models.TextField(blank=True, default='', verbose_name='Suspension reason')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone number')),
                ('role', models.CharField(blank=True, choices=[('member', 'Member'), ('manager', 'Manager')], default='', max_length=30, verbose_name='Role')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted at')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login history',
                'verbose_name_plural': 'login history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_phone_when_set'),
        ),
    ]
