# Generated by Django 5.1.11 on 2026-06-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'login record', 'verbose_name_plural': 'login history'},
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logged out at'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Logged in at'),
        ),
    ]
